### ISSUE TITLE
Compatibility with Unloaded Activity

### ISSUE THREAD

**Issue by jshipley** [PaddedShaman/BlazingBamboo#1]
Version 1.20.1-1.0.1

When the Unloaded Activity mod is installed, the blazing bamboo is replaced by regular bamboo when the player sleeps.

**Comment by jshipley** [comment]
This is happening on Fabric, Forge, and Neoforge.

**Comment by jshipley** [comment]
Nevermind. If this is going to be fixed, it would probably need to be fixed in the Unloaded Activity mod.

It's setting the block state for BambooShootBlock and BambooSaplingBlock to the default blockstate of Blocks.BAMBOO.

Since the Blazing Bamboo extends those classes, the mixin from Unloaded Activity sets the Blazing Bamboo blockstate to the vanilla bamboo blockstate.

**Comment by jshipley** [comment]
https://github.com/InZan17/Unloaded-Activity/issues/27

**Comment by PaddedShaman** [comment]
Thanks for the heads-up!

I looked at it as well and yeah, the BambooMixin and BambooSaplingMixin could use `this.getDefaultBlockState` for compatibility with modded bamboo, similar to how it's done in the CropBlockMixin, which makes it compatible with modded crops that extend CropBlock.

Modded bamboo is really uncommon compared to modded crops, but there's at least one other mod, Ferdinand's Flowers, which implements custom bamboo types that extend the vanilla bamboo classes. The same thing happens when using Unloaded Activity with Ferdinand's Flowers in Forge 1.19.2: sleeping or otherwise advancing time replaces the custom bamboo with vanilla bamboo.

I could also rewrite Blazing Bamboo without extending BambooBlock and BambooSaplingBlock, just have them extend Block. I will try to do this if it's not feasible for Zan to resolve it in Unloaded Activity; then at least the mods could be installed together and function separately.

**Comment by PaddedShaman** [comment]
Fixed in Unloaded Activity.
